#!/usr/bin/sh

CPU="$(top -bn 1 | grep '%Cpu' | tr -d 'usy,' | awk '{print "user " $2 ", sys " $3}')"
KERNEL="$(uname -r)"
MEMORY="$(free -h | awk '/^Mem:/ {print $3 "/" $2}')"
VOLUME="$(amixer get Master | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/')"
UPTIME="$(uptime --pretty | sed -e 's/up //g' \
                                -e 's/ days/d/g' \
                                -e 's/ day/d/g' \
                                -e 's/ hours/h/g' \
                                -e 's/ hour/h/g' \
                                -e 's/ minutes/m/g' \
                                -e 's/, / /g')"
DATE="$(date +"%a, %B %d %l:%M%p"| sed 's/  / /g')"


echo -e "cpu: $CPU | memory: $MEMORY | volume: $VOLUME | uptime: $UPTIME | data: $DATE"
