#!/bin/bash
running=$(ps h -C xautolock | grep -wv $$ | wc -l);
[[ $running < 1 ]] && notify-send.sh "Inhibitor Already Active"&& exit;

notify-send.sh "Inhibitor" "Activated"
pkill xautolock && xset s 0
